# Provides utilities to control clang-tidy as part of the build process. It is
# recommended to include this file in the top-level CMakeLists.
#
# To exclude files/directories from clang-tidy checks, see the utility functions
# below or add a .clang-tidy configuration file with:
#
# Checks: '-*'
#
# in the directory you want to exclude. See clang-tidy documentation for more
# information.
#
# Below is a list of variables which control the default result of running
# utilities in this file:
#
# CLANG_TIDY_AUTORUN                  - define to enable automatic clang-tidy
# runs during build. CLANG_TIDY_CACHE_DIR                - path to directory for
# temporary clang-tidy files. CLANG_TIDY_EXCLUDES_FILEPATH        - path to a
# file with file/directory path expressions to exclude from clang-tidy checks.
# CLANG_TIDY_RUNNER_CONFIG_FILE       - path to clang_tidy_runner configuration
# file. Run clang_tidy_runner --help for details.

if(NOT TARGET _clang_tidy_init_marker)
  add_library(_clang_tidy_init_marker INTERFACE)

  # Set the directory path for temporary clang-tidy files.
  if(NOT DEFINED CLANG_TIDY_CACHE_DIR)
    set(CLANG_TIDY_CACHE_DIR "${CMAKE_BINARY_DIR}/ci/clang_tidy")
  endif()

  # Set the excludes file path.
  if(NOT DEFINED CLANG_TIDY_EXCLUDES_FILEPATH)
    set(CLANG_TIDY_EXCLUDES_FILEPATH "${CLANG_TIDY_CACHE_DIR}/excludes.txt")
  endif()

  # Set the clang_tidy_runner configuration file path.
  if(NOT DEFINED CLANG_TIDY_RUNNER_CONFIG_FILE)
    set(CLANG_TIDY_RUNNER_CONFIG_FILE "${CLANG_TIDY_CACHE_DIR}/config")
  endif()

  # Overwrite the file with excludes on each new build. Write CMake build
  # directory path to the list of excludes.
  file(WRITE "${CLANG_TIDY_EXCLUDES_FILEPATH}" "${CMAKE_BINARY_DIR}.*")

  # Function: clang_tidy_exclude_file Description: Exclude the file in
  # ${CMAKE_CURRENT_LIST_DIR} with the given filename from clang-tidy checks.
  #
  # Arguments: <filename> - Name of the file in ${CMAKE_CURRENT_LIST_DIR}.
  #
  # Usage: clang_tidy_exclude_file(<filename>)
  #
  # Example: clang_tidy_exclude_file(Servo.cpp) message(STATUS "Will not check
  # ${CMAKE_CURRENT_LIST_DIR}/Servo.cpp")
  function(clang_tidy_exclude_file filename)
    set(FILE_ABSOLUTE_PATH "${CMAKE_CURRENT_LIST_DIR}/${filename}")
    if(NOT EXISTS "${FILE_ABSOLUTE_PATH}")
      message(SEND_ERROR "${CMAKE_CURRENT_FUNCTION}: "
                         "file does not exist: ${FILE_ABSOLUTE_PATH}")
      return()
    endif()

    if(EXISTS "${CLANG_TIDY_EXCLUDES_FILEPATH}")
      file(APPEND "${CLANG_TIDY_EXCLUDES_FILEPATH}" "\n")
    endif()

    file(APPEND "${CLANG_TIDY_EXCLUDES_FILEPATH}" "${FILE_ABSOLUTE_PATH}")
  endfunction()

  # Function: clang_tidy_exclude_subdirectory Description: Exclude the
  # subdirectory in ${CMAKE_CURRENT_LIST_DIR} with the given name from
  # clang-tidy checks. Subdirectory contents, including directories inside it
  # are recursively excluded as well.
  #
  # Arguments: <dirname> - The name of the subdirectory in
  # ${CMAKE_CURRENT_LIST_DIR}.
  #
  # Usage: clang_tidy_exclude_subdirectory(<dirname>)
  #
  # Example: clang_tidy_exclude_subdirectory(examples) message(STATUS "Will not
  # check ${CMAKE_CURRENT_LIST_DIR}/examples/*")
  #
  # clang_tidy_exclude_subdirectory(external/lufa) message(STATUS "Will not
  # check external/lufa/*")
  function(clang_tidy_exclude_subdirectory dirname)
    set(DIR_ABSOLUTE_PATH "${CMAKE_CURRENT_LIST_DIR}/${dirname}")
    if(NOT EXISTS "${DIR_ABSOLUTE_PATH}")
      message(SEND_ERROR "${CMAKE_CURRENT_FUNCTION}: "
                         "directory does not exist: ${DIR_ABSOLUTE_PATH}")
      return()
    endif()

    if(EXISTS "${CLANG_TIDY_EXCLUDES_FILEPATH}")
      file(APPEND "${CLANG_TIDY_EXCLUDES_FILEPATH}" "\n")
    endif()

    # The runner script will use entries in the excludes file as parts of its
    # regexps for filtering source files. This requires a trailing `.*` to mark
    # this entry as a directory.
    file(APPEND "${CLANG_TIDY_EXCLUDES_FILEPATH}" "${DIR_ABSOLUTE_PATH}.*")
  endfunction()

  # Function: clang_tidy_generate_config Description: Generate and write
  # clang_tidy_runner configuration file to ${CLANG_TIDY_RUNNER_CONFIG_FILE}.
  #
  # Arguments: USE_COMPILE_COMMANDS - Optional. If given, use the compilation
  # database generated by CMake for the clang_tidy_runner.
  #
  # Usage: clang_tidy_generate_config([USE_COMPILE_COMMANDS])
  #
  # Example: clang_tidy_generate_config()
  #
  # clang_tidy_generate_config(USE_COMPILE_COMMANDS)
  function(clang_tidy_generate_config)
    set(ARGS "${ARGN}")
    list(LENGTH ARGS ARGS_COUNT)

    if("${ARGS_COUNT}" GREATER 0)
      list(GET ARGS 0 ARG)

      # Check if a single optional argument matches the required name.
      if(NOT ARG STREQUAL "USE_COMPILE_COMMANDS")
        message(SEND_ERROR "${CMAKE_CURRENT_FUNCTION}: "
                           "USE_COMPILE_COMMANDS optional arg is allowed only")
        return()
      endif()

      file(
        WRITE "${CLANG_TIDY_RUNNER_CONFIG_FILE}"
        "#!/bin/sh \
                \nclang_tidy_exe=clang-tidy \
                \n \
                \nexclude_path=${CMAKE_BINARY_DIR}/ci/clang_tidy/excludes.txt \
                \nbuild_path=${CMAKE_BINARY_DIR} \
                \nre_pattern=\"^${CMAKE_SOURCE_DIR}.*\\.\\(h\\|hpp\\|c\\|cpp\\)\$\" \
                \nre_escape=false \
                \nparallel=false \
                \nverbose=false \
                \nverbose_nn=10 # Has effect in verbose mode only. \
                \n# clang_tidy_args=\" \
                \n# --header-filter=\"^${CMAKE_SOURCE_DIR}*\" \
                \n# --use-color \
                \n# --checks=\"-*\" \
                \n# --allow-no-checks \
                \n# \" \
                \nclang_tidy_args=\" \
                \n--header-filter=\"^${CMAKE_SOURCE_DIR}.*\" \
                \n--use-color \
                \n\" \
                \n \
                \ncompiler=arm-none-eabi-gcc \
                \ncompile_commands_filename=compile_commands.json \
                \n")
    else()
      file(
        WRITE "${CLANG_TIDY_RUNNER_CONFIG_FILE}"
        "#!/bin/sh \
                \nclang_tidy_exe=clang-tidy \
                \n \
                \nexclude_path=${CMAKE_BINARY_DIR}/ci/clang_tidy/excludes.txt \
                \nbuild_path= \
                \nre_pattern=\"^${CMAKE_SOURCE_DIR}.*\\.(h|hpp|c|cpp)\$\" \
                \nre_pattern=\"^${CMAKE_SOURCE_DIR}.*\\.\\(h\\|hpp\\|c\\|cpp\\)\$\" \
                \nre_escape=false \
                \nparallel=false \
                \nverbose=false \
                \nverbose_nn=10 # Has effect in verbose mode only. \
                \n# clang_tidy_args=\" \
                \n# --header-filter=\"^${CMAKE_SOURCE_DIR}.*\" \
                \n# --use-color \
                \n# --checks=\"-*\" \
                \n# --allow-no-checks \
                \n# \" \
                \nclang_tidy_args=\" \
                \n--header-filter=\"^${CMAKE_SOURCE_DIR}.*\" \
                \n--use-color \
                \n\" \
                \n \
                \ncompiler=arm-none-eabi-gcc \
                \ncompile_commands_filename=compile_commands.json \
                \n")
    endif()
  endfunction()

  # Function: clang_tidy_enable Description: Enable clang_tidy_runner to become
  # part of the build process. If ${CLANG_TIDY_AUTORUN} is defined,
  # automatically runs clang-tidy checks during CMake build. Otherwise, a custom
  # target is created and can be executed with:
  #
  # cmake --build build --target clang-tidy
  #
  # Usage: clang_tidy_enable()
  #
  # Example: clang_tidy_enable()
  function(clang_tidy_enable)
    # Generate a default configuration file for the runner. This will overwrite
    # any previously generated configs.
    if(DEFINED CMAKE_EXPORT_COMPILE_COMMANDS AND CMAKE_EXPORT_COMPILE_COMMANDS)
      clang_tidy_generate_config(USE_COMPILE_COMMANDS)
    else()
      clang_tidy_generate_config()
    endif()

    if(DEFINED CLANG_TIDY_AUTORUN AND CLANG_TIDY_AUTORUN)
      add_custom_target(
        clang-tidy ALL
        COMMAND
          cd "${CMAKE_SOURCE_DIR}" && echo
          "Running clang-tidy as part of the build process" &&
          "${CMAKE_SOURCE_DIR}/scripts/clang_tidy_runner.sh" --config
          "${CLANG_TIDY_RUNNER_CONFIG_FILE}")
    else()
      message(STATUS "${CMAKE_CURRENT_FUNCTION}: "
                     "clang_tidy_runner will not run automatically. "
                     "Run `cmake --build build --target clang-tidy`")
      add_custom_target(
        clang-tidy
        COMMAND
          cd "${CMAKE_SOURCE_DIR}" && echo "Running clang-tidy runner target"
          && "${CMAKE_SOURCE_DIR}/scripts/clang_tidy_runner.sh" --config
          "${CLANG_TIDY_RUNNER_CONFIG_FILE}")
    endif()
  endfunction()
endif()
